const Data = [
  {
    id: 1,
    title:"ASUS TUF Gaming F15 Gaming Laptop, 15.6” 144Hz FHD IPS-Type Display, Intel Core i5-10300H Processor, GeForce GTX 1650, 8GB DDR4 RAM, 512GB PCIe SSD, Wi-Fi 6, Windows 11 Home, FX506LH-AS51",
    description: "ASUS TUF Gaming F15 is a powerful Windows 10 gaming laptop that combines gaming performance with up to a narrow bezel IPS-type panel and an extended lifespan, thanks to its patented Anti-Dust Cooling (ADC) system. Equipped with NVIDIA GeForce graphics, 11th Generation Intel Core processor, and solid-state storage, the F15 is able to play the latest games and multitask with ease. To top it all off, it’s backlit gaming keyboard is rated at 20-million keystroke durability.",
    price: "649.99",
    category: "Laptop",
    image: "./img/L1_.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "Acer Nitro 5 AN515-57-79TD Gaming Laptop | Intel Core i7-11800H | NVIDIA GeForce RTX 3050 Ti Laptop GPU | 15.6 FHD 144Hz IPS Display | 8GB DDR4 | 512GB NVMe SSD | Killer Wi-Fi 6 | Backlit Keyboard",
    description: "Acer gaming laptops deliver advanced performance for all gamers. The Nitro lineup of gaming PCs and accessories are ideal for casual gamers who are ready for something better. The Acer Nitro 5 AN515-57 is equipped with a beautiful 15.6 inch FHD display to help you visualize the win. The latest NVIDIA GeForce RTX 30 series GPU supports 2nd Gen Ray Tracing Cores, 3rd Gen Tensor Cores, DLSS, Resizable BAR, Microsoft DirectX 12 Ultimate, and so much more. With Killer's DoubleShot Pro and Wi-Fi 6, get quicker matchmaking and never worry about disconnecting during a game. The Acer Nitro 5 11th Gen Intel Core i7 processing power enables impressive performance whether you're challenging your buddies to battle or focusing on a new hobby. This Acer Nitro laptop is configured with 8GB RAM memory and 512GB solid-state drive storage space, and the ability to upgrade as needed. Use the HDMI 2.1 port for a monitor, use power-off USB charging, and get the best of USB with the USB-Type-C port. (NH.QESAA.005)",
    price: "910.89",
    category: "Laptop",
    image: "./img/L2_.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "Acer Predator Helios 300 PH315-54-760S Gaming Laptop | Intel i7-11800H | NVIDIA GeForce RTX 3060 Laptop GPU | 15.6 FHD 144Hz 3ms IPS Display | 16GB DDR4 | 512GB SSD | Killer WiFi 6 | RGB Keyboard",
    description: "Acer gaming laptops deliver advanced performance for all gamers. The Predator lineup of gaming PCs and accessories are ideal for everyday gamers who need powerful products that can handle daily use and overclocking. The Acer Predator Helios 300 PH315-54 is powered up with the latest 11th Generation Intel Core i7 processor, giving you power, speed, and intelligent processing when you need it most. The new NVIDIA GeForce 30 Series graphics card is powered by award-winning Ampere architecture, and boasts new Ray Tracing cores, Tensor cores, and streaming multiprocessors for realistic graphics. The incredibly fast 144Hz refresh rate will keep up with your beautiful graphics in crisp Full HD for high-octane gameplay. When you're playing online, Intel Killer DoubleShot Pro keeps you connected to your match or chatroom by allowing your Predator laptop to use both Ethernet and Wi-Fi at the same time. This Predator gaming notebook is also equipped with hardware that can keep up with the powerful internal specs. Our specially engineered 5th Generation AeroBlade 3D Fan uses wind-guiding Vortex Flow to increase airflow and cooling from intake to exhaust, so your computer stays cool no matter the task. Our customized keyboard has see-through concave-shaped WASD keycaps, and dedicated keys for Turbo overclocking and PredatorSense. PredatorSense is the ultimate tool to let you control and customize your gaming laptop, from overclocking to fan speed to game profiles and more. (NH.QC2AA.003).",
    price: "1.217",
    category: "Laptop",
    image: "./img/L3_.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Razer Blade 17 Gaming Laptop: NVIDIA GeForce RTX 3080 Ti - 12th Gen Intel 14-Core i9 CPU - 17.3 4K 144Hz - 32GB DDR5 RAM - 1TB PCIe SSD - Windows 11 - Chroma RGB - Thunderbolt 4 - SD Card Reader",
    description: "Within its sleek 15” chassis, the new Razer Blade 17 is equipped with the latest Intel 12th Gen H-Series processors for maximum performance. Paired with NVIDIA’s GeForce RTX 30 Ti series graphics for stunning visuals that are brought to life with a variety of displays.",
    price: "4.299",
    category: "Laptop",
    image: "./img/L4_.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "2022 Flagship Acer 311 Chromebook 11.6 HD Display Laptop Student Business, MediaTek MT8183C 8-Core Processor, 4GB RAM, 32GB eMMC, Wi-Fi 5, Webcam, Upto 15 Hours Battery, Chrome OS+HubxcelAccessories",
    description: "The 2022 Newest Acer Chromebook 311 is the ideal laptop for all ages from the very young upwards. Weighing in at just 2.2lbs., it’s ultra-light and easily transported in a backpack or bag. The power efficient MediaTek MT8183C processor and generous battery give it up to 15 hours of battery life, meaning a full charge will easily last the working day and all evening.",
    price: "189.00",
    category: "Laptop",
    image: "./img/L5_.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "Razer Blade 15 Base Gaming Laptop 2020: Intel Core i7-10750H 6-Core, NVIDIA GeForce RTX 2060, 15.6 FHD 1080p 144Hz, 16GB RAM, 512GB SSD, CNC Aluminum, Chroma RGB Lighting, Thunderbolt 3, Black",
    description: "The new Razer Blade 15 is an ultra-compact NVIDIA GeForce RTX 2060 powered laptop that features the latest 10th Gen Intel Core i7 6-core processor, to deliver amazing performance and portability. The 15. 6 144Hz thin bezel, Full HD display provides an immersive and insanely fast visual experience for gaming and beyond.",
    price: "1.799",
    category: "Laptop",
    image: "./img/L6_.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "SENZER SG500 Surround Sound Pro Gaming Headset with Noise Cancelling Microphone - Detachable Memory Foam Ear Pads - Portable Foldable Headphones for PC, PS4, PS5, Xbox One, Switch",
    description: "[FOLDABLE & DETACHABLE EAR PADS]: Features flexible headphones with telescopic arms and detachable ear pads. The headphones fold inside the arm, making them perfect for easy storage and travelling and the ear pads are magnetic, allowing them to be conveniently attached and removed, making them easier to clean and maintain compared with other headphones.",
    price: "29.99",
    category: "Headsets",
    image: "./img/H1_.jpg",
    quantity: 1,
  },
  {
    id: 8,
    title: "Razer BlackShark V2 Gaming Headset: THX 7.1 Spatial Surround Sound - 50mm Drivers - Detachable Mic - PC, PS4, PS5, Switch, Xbox One, Xbox Series X & S, Mobile - 3.5 mm Audio Jack & USB DAC - Black",
    description: "The Best-Selling Gaming Peripherals Brand: Source - The NPD Group, Inc. U.S. Retail Tracking Service: Gaming Keyboards, Gaming Mice, Gaming Headsets, Gaming Peripherals; Based on dollar sales, Jan-Sept. 2021 combined",
    price: "79.99",
    category: "Headsets",
    image: "./img/H2_.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "BENGOO G9000 Stereo Gaming Headset for PS4 PC Xbox One PS5 Controller, Noise Cancelling Over Ear Headphones with Mic, LED Light, Bass Surround, Soft Memory Earmuffs for Laptop Mac Nintendo NES Games",
    description: "【Surrounding Stereo Subwoofer】Clear sound operating strong brass, splendid ambient noise isolation and high precision 40mm magnetic neodymium driver, acoustic positioning precision enhance the sensitivity of the speaker unit, bringing you vivid sound field, sound clarity, shock feeling sound. Perfect for various games like Halo 5 Guardians, Metal Gear Solid, Call of Duty, Star Wars Battlefront, Overwatch, World of Warcraft Legion, etc.",
    price: "23.99",
    category: "Headsets",
    image: "./img/H3_.jpg",
    quantity: 1,
  },
  {
    id: 10,
    title: "Logitech G733 LIGHTSPEED Wireless Gaming Headset with suspension headband, LIGHTSYNC RGB, Blue VO!CE mic technology and PRO-G audio drivers - White",
    description: "Total freedom with up to 20 m wireless range and LIGHTSPEED wireless audio transmission. Keep playing for up to 29 hours of battery life. 1 Play in stereo on PlayStation(R) 4.",
    price: "147.50",
    category: "Headsets",
    image: "./img/H4_.jpg",
    quantity: 1,
  },
  {
    id: 11,
    title: "Logitech G435 LIGHTSPEED and Bluetooth Wireless Gaming Headset - Lightweight over-ear headphones, built-in mics, 18h battery, compatible with Dolby Atmos, PC, PS4, PS5, Nintendo Switch, Mobile - White",
    description: "Total comfort: Breathable fabric earcups keep your ears cool during long play sessions, and the comfortable memory foam padding helps absorb sound waves to improve overall sound",
    price: "200",
    category: "Headsets",
    image: "./img/H5_.jpg",
    quantity: 1,
  },
  {
    id: 12,
    title: "Razer Kraken Gaming Headset: Lightweight Aluminum Frame, Retractable Noise Isolating Microphone, For PC, PS4, PS5, Switch, Xbox One, Xbox Series X & S, Mobile, 3.5 mm Audio Jack – Green",
    description: "Immersive, 7.1 Surround Sound for Positional Audio: Outfitted with custom-tuned 50 millimeter drivers, capable of software-enabled surround sound (only available on Windows 10 64-bit)",
    price: "44.99",
    category: "Headsets",
    image: "./img/H6_.jpg",
    quantity: 1,
  },
  {
    id: 13,
    title: "Microsoft Xbox Series S Console - 512GB(Renewed)",
    description: "This pre-owned or refurbished product has been professionally inspected and tested to work and look like new. How a product becomes part of Amazon Renewed, your destination for pre-owned, refurbished products: A customer buys a new product and returns it or trades it in for a newer or different model. That product is inspected and tested to work and look like new by Amazon-qualified suppliers. Then, the product is sold as an Amazon Renewed product on Amazon. If not satisfied with the purchase, renewed products are eligible for replacement or refund under the Amazon Renewed Guarantee.",
    price: "289.00",
    category: "XBox",
    image: "./img/xbox1.jpg",
    quantity: 1,
  },
  {
    id: 14,
    title: "Xbox Series S – Fortnite & Rocket League Bundle",
    description: "Get the all-digital Xbox Series S – Fortnite & Rocket League Bundle featuring the Midnight Drive Pack, 1,000 V-Bucks, and 1,000 Rocket League credits. With the Midnight Drive Pack for Fortnite, you can customize your avatar with the Dark Skully outfit, Dark Skully Satchel Back Bling, Dark Splitter pickaxe, and 1,000 V-Bucks to spend on favorite items in Fortnite Battle Royale and more. For Rocket League add-on content, you get the standout Purple Masamune Car, Purple Virtual Wave Boost, Purple Zefram Wheels, and 1,000 Rocket League Credits that can be used to build Blueprints, upgrade to Rocket Pass Premium, or purchase most-wanted content from the Rocket League Item Shop. And, since Fortnite and Rocket League are free-to-play with Xbox, you can get right to gaming with friends.",
    price: "306.00",
    category: "XBox",
    image: "./img/xbox2.jpg",
    quantity: 1,
  },
  {
    id: 15,
    title: "Xbox Series X 1TB Black (Renewed)",
    description: "This pre-owned or refurbished product has been professionally inspected and tested to work and look like new. How a product becomes part of Amazon Renewed, your destination for pre-owned, refurbished products: A customer buys a new product and returns it or trades it in for a newer or different model. That product is inspected and tested to work and look like new by Amazon-qualified suppliers. Then, the product is sold as an Amazon Renewed product on Amazon. If not satisfied with the purchase, renewed products are eligible for replacement or refund under the Amazon Renewed Guarantee.",
    price: "499.99",
    category: "XBox",
    image: "./img/xbox3.jpg",
    quantity: 1,
  },
  {
    id: 16,
    title: "Microsoft FMQ-00042 Console, 18.5 x 12 x 5, Black",
    description: "Microsoft Xbox One X 1TB Console",
    price: "449",
    category: "XBox",
    image: "./img/xbox4.jpg",
    quantity: 1,
  },
  {
    id: 17,
    title: "Microsoft Xbox 360 Slim System w/320GB HDD HDMI Port & Optical Audio - Unit Only",
    description: "This is NOT a unit only. This system comes with 2 controllers, the Xbox 360 headset, AV cable, HDMI cable, power supply and Forza 4.",
    price: "209.29",
    category: "XBox",
    image: "./img/xbox5.jpg",
    quantity: 1,
  },
  {
    id: 18,
    title: "Xbox 360 Slim 250GB Console",
    description: "This is NOT a unit only. This system comes with 2 controllers, the Xbox 360 headset, AV cable, HDMI cable, power supply and Forza 4.",
    price: "189",
    category: "XBox",
    image: "./img/xbox6.jpg",
    quantity: 1,
  },
  {
    id: 19,
    title: "Sony Playstation 3 320GB PS3 Console Only (Renewed)",
    description: "The PS3 system is now slimmer and lighter than ever before. While the form factor may have changed, the PS3 system still comes with free access to the PlayStation Network, built-in Wi-Fi, and hard disk drive storage for games, music, videos, and photos. Plus, the PS3 system is the only gaming console with a Blu-ray player to give you the best high-definition viewing experience on your television. With five times the capacity of standard DVDs, Blu-ray discs gives you more realistic and immersive gameplay that can only be possible on the PS3 system with games such as Gran Turismo 5, Uncharted 2: Among Thieves Game of the Year, and MAG. All PlayStation 3 systems are already equipped with everything you need to play stereoscopic 3D games.",
    price: "300",
    category: "Playstation",
    image: "./img/p1.jpg",
    quantity: 1,
  },
  {
    id: 20,
    title: "Newest Sony Playstation 4 Slim 1TB SSD Console - Marvel's Spider-Man PS4 Bundle with DualShock-4 Wireless Controller",
    description: "support 2 x Super-Speed USB (USB 3.1 Gen.1) Port, 1 x AUX Port, HDMI Out Port (Supports 4K/HDR), Digital Out (Optical) Port, Memory Card Support",
    price: "442.50",
    category: "Playstation",
    image: "./img/p2.jpg",
    quantity: 1,
  },
  {
    id: 21,
    title: "Flagship Newest Play Station 4 1TB HDD Only on Playstation PS4 Console Slim Bundle with Three Games: The Last of Us, God of War, Horizon Zero Dawn 1TB HDD Dualshock 4 Wireless Controller -Jet Black",
    description: "Play Station 4 1TB HDD Only on Playstation PS4 Console Slim Bundle with Three Games: The Last of Us, God of War, Horizon Zero Dawn 1TB HDD Dualshock 4 Wireless Controller -Jet Black",
    price: "327.41",
    category: "Playstation",
    image: "./img/p3.jpg",
    quantity: 1,
  },
  {
    id: 22,
    title: "PlayStation 5 Console Horizon Forbidden West Bundle - PS5 Disc Version 4K 120Hz HDR 825 GB SSD 3D Audio",
    description: "The PS5 console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation games. 3D audio via built-in TV speakers or analog/USB stereo headphones.",
    price: "889",
    category: "Playstation",
    image: "./img/p4.jpg",
    quantity: 1,
  },
  {
    id: 23,
    title: "Sony Playstation 4 Slim Video Game Console 500GB Jet Black PS4",
    description: "The Best Place to Play PlayStation 4 is the best place to play with dynamic, connected gaming, powerful graphics and speed, intelligent personalization, deeply integrated social capabilities, and innovative second-screen features. Combining unparalleled content, immersive gaming experiences, all of your favorite digital entertainment apps, and PlayStation exclusives, PS4 centers on gamers, enabling them to play when, where and how they want. PS4 enables the greatest game developers in the world to unlock their creativity and push the boundaries of play through a system that is tuned specifically to their needs.",
    price: "325.99",
    category: "Playstation",
    image: "./img/p5.jpg",
    quantity: 1,
  },
  {
    id: 24,
    title: "High-Back Gaming Chair PC Office Chair Computer Racing Chair PU Desk Task Chair Ergonomic Executive Swivel Rolling Chair with Lumbar Support for Back Pain Women, Men (White)",
    description: "Brand new and high quality, luxury racing car style office chair, high back, comfortable arm rests, black metal star base and adjustable height gas-spring, comfortable backrest. This desk chair gives you excellent seating experience while you working or relaxing.",
    price: "99.98",
    category: "Chair",
    image: "./img/ch1.jpg",
    quantity: 1,
  },
  {
    id: 25,
    title: "RESPAWN 110 Ergonomic Gaming Chair with Footrest Recliner - Racing Style High Back PC Computer Desk Office Chair - 360 Swivel, Adjustable Lumbar Support, Headrest Pillow, Padded Armrests - 2019 Camo",
    description: "You’re a gamer first, you shouldn’t have to spend the cost of an ultrawide monitor to get an ergonomic gaming chair. The RESPAWN 110 delivers comfort and cost savings in one package. The chair tilt and lift levers are located on the right, beneath the chair, and the fixed armrests are padded for elbow relief. The RSP-110 features a soft touch polyester Forest Camo pattern inlay and a 155-degree tilt, with infinite angle lock, allowing you to choose your best angle. The adjustable lumbar and head pillow gives you the support you need for long hours in any game. Put your feet up and relax with a built-in extendable footrest. An award-nominated brand, RESPAWN is committed to your satisfaction and covers this desk with our RESPAWN 5-Year Limited Warranty. With a 275 lb weight capacity, this RESPAWN gaming chair helps you bring your ‘A’ game to every match.",
    price: "209.45",
    category: "Chair",
    image: "./img/ch2.jpg",
    quantity: 1,
  },
  {
    id: 26,
    title: "AIMU Gaming Chairs Ergonomic Office Chair Video Game Chairs with Footrest High Back Computer Chair Headrest and Lumbar Support Reclining Racing Chair Desk Chair for Men Women (Pink and White)",
    description: "S*MAX Gaming Chair designed with 5.5 Thickened Molded Foam Cushion ,3D armrest, Thicker Headrest and Lumbar Support, Thicker Side Wings, Premium PU leather. S*MAX Gaming Chair brings you all-round body support and the ultimate gaming experience. 5.5 Thickened cushion is suitable for sitting long periods of time.",
    price: "199.99",
    category: "Chair",
    image: "./img/ch3.jpg",
    quantity: 1,
  },
  {
    id: 27,
    title: "Gaming Chair Office Chair High Back Computer Chair Leather Desk Chair Mesh Ergonomic Adjustable Swivel Task Chair with Headrest and Lumbar Support, 400lb Capacity,Red",
    description: "YSSOA gaming chair extends the full length of the chair to support the shoulders, head, and neck. Brand new and high quality video game chair, comes with comfortable arm rests, sturdy metal base and adjustable height gas-spring to provide you with an excellent seating experience when you work or relax.",
    price: "115.99",
    category: "Chair",
    image: "./img/ch4.jpg",
    quantity: 1,
  },
  {
    id: 28,
    title: "High-Back Gaming Chair PC Office Chair Computer Racing Chair PU Desk Task Chair Ergonomic Executive Swivel Rolling Chair with Lumbar Support for Back Pain Women, Men (Blue)",
    description: "Racing Office Chair: Office chair has fashion upholstery, beautifully designed and thickness padded, fits the sitting position of human thigh that would provided you a comfortable seat.",
    price: "149.99",
    category: "Chair",
    image: "./img/ch5.jpg",
    quantity: 1,
  },
  {
    id: 29,
    title: "AutoFull Gaming Chair 4.3in Seat Cushion Ergonomic Gamer Chair High Back Computer Gaming Chair Wear-Resistant Super Soft PU Leather with Headrest and Lumbar Support Racing Gaming Chair, Ice Blue",
    description: "Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.",
    price: "279.99",
    category: "Chair",
    image: "./img/ch6.jpg",
    quantity: 1,
  },

];


export default Data